const originalRepresentativesData = {
    "1": "Padre", "2": "Madre", "3": "Abuelo Paterno", "4": "Abuela Paterna", "5": "Padre de Abuelo Paterno", "6": "Madre de Abuelo Paterno", "7": "Padre de Abuela Paterna", "8": "Madre de Abuela Paterna", "9": "4ta Generación Paterna (varón)", "10": "4ta Generación Paterna (mujer)", "11": "Abuelo Materno", "12": "Abuela Materna", "13": "Padre de Abuelo Materno", "14": "Madre de Abuelo Materno", "15": "Padre de Abuela Materna", "16": "Madre de Abuela Materna", "17": "4ta Generación Materna (varón)", "18": "4ta Generación Materna (mujer)", "19": "Bisabuelo/a", "20": "Tatarabuelo/a", "21": "Padres adoptivos", "22": "Padrastro / Madrastra", "23": "Donante", "24": "Ancestro omitido/excluido", "25": "Hermano/a", "26": "Hermano/a fallecido/a", "27": "Hermano/a no nacido/a", "28": "Medio hermano/a", "29": "Hermano/a gemelo/a o mellizo/a", "30": "Primos hermanos", "31": "Tío/a", "32": "Sobrinos/as", "33": "Cuñados/as", "34": "Hijo/a", "35": "Hijo/a fallecido/a", "36": "Hijo/a abortado/a", "37": "Hijo/a no reconocido/a", "38": "Nieto/a", "39": "Bisnieto/a", "40": "Hijos adoptivos", "41": "Hijos no nacidos por intención", "42": "Pareja actual", "43": "Parejas anteriores con hijos", "44": "Esposo/a", "45": "Abuelos adoptivos (rol)", "46": "Tíos abuelos (rol)", "47": "Perpetrador", "48": "Magia oscura en el sistema", "49": "victima", "50": "Secretos en el arbol", "51": "Te protejemos desde la Luz", "52": "Ajenos al sistema que fueron incluidos", "53": "Aun no esta listo para mostrarse", "54": "Abusados de diferentes maneras puede ser fisica psiquica o mental", "55": "Me siento en peligro", "56": "Desaparecidos", "57": "Caidos", "58": "Traiciones al sistema", "59": "Personas desplazadas o migrantes", "60": "Expulsados / excluidos por normas sociales o familiares", "61": "Enfermos crónicos / discapacitados", "62": "Suicidas", "63": "Abortos naturales", "64": "Niños entregados en adopción", "65": "Excluidos por religión o creencias", "66": "Pueblos originarios o ancestros no reconocidos", "67": "Amantes ocultos / relaciones secretas", "68": "Personas encarceladas", "69": "Victimarios del propio clan", "70": "Guerreros / combatientes sobrevivientes", "71": "Sacrificados por otros", "72": "Dinero o bienes perdidos", "73": "Líderes o figuras de poder en el clan", "74": "Personas con dones espirituales o místicos", "75": "Víctimas de abusos de poder fuera del clan"
};

const originalStellarCodesData = {
    "1": { "id": "emotion-1", "title": "Herida primaria de origen", "phrase": "“Me anclo al dolor de cómo empezó todo”", "act": "Frase: Me libero del anclaje al dolor del pasado. Reconozco que cada inicio, aunque difícil, me ha fortalecido. Honro mi historia y elijo crear un nuevo inicio, lleno de luz y esperanza. Mi presente es mi poder. Me doy permiso para reescribir mi historia desde el amor y la paz. Mi origen no me define, mi evolución sí. Gracias por mostrarme el camino. Gracias por hacérmelo saber. Ahora entiendo. Ahora los veo. Ahora elegimos la vida. Dejo en el pasado con ustedes lo que es de ustedes. Y reclamo lo que me corresponde por derecho divino. Gracias, gracias, gracias.", "colorClass": "emotion-color-1" },
    "2": { "id": "emotion-2", "title": "Miedo ancestral a fallar", "phrase": "“Si lo hago mal, destruyo todo”", "act": "Frase: Rompo el miedo ancestral al fracaso. Entiendo que mis acciones son parte de un aprendizaje, no de una destrucción. Cada error es un paso hacia el crecimiento. Me perdono por no ser perfecto y me libero de la carga de tener que hacerlo todo bien. Me atrevo a intentar, a equivocarme y a volver a empezar, porque mi valor no se mide por mis fallos. El fracaso es un maestro. Elijo la valentía en lugar del miedo. Gracias por mostrarme el camino. Gracias por hacérmelo saber. Ahora entiendo. Ahora los veo. Ahora elegimos la vida. Dejo en el pasado con ustedes lo que es de ustedes. Y reclamo lo que me corresponde por derecho divino.", "colorClass": "emotion-color-2" },
    "360": {
        "id": "systemic-360",
        "title": "Miedo a no ser suficiente",
        "phrase": "“Nunca seré suficiente para los demás.”",
        "act": "Frase: Reconozco las creencias de insuficiencia que me han limitado. Hoy elijo reconocer mi valor y saber que soy suficiente. Con amor ahora elijo la suficiencia personal. Con amor ahora elegimos la vida. Reclamo mi valor incondicional por derecho divino.",
        "colorClass": "systemic-color-3"
    }
};
